// Auto-generated by scripts/kpi_analysis.py -- do not edit by hand.
const DASHBOARD_DATA = {
  "generated_from": "monthly_actuals.csv / monthly_budget.csv / order_line_items.csv",
  "months": [
    "Jan 2025",
    "Feb 2025",
    "Mar 2025",
    "Apr 2025",
    "May 2025",
    "Jun 2025",
    "Jul 2025",
    "Aug 2025",
    "Sep 2025",
    "Oct 2025",
    "Nov 2025",
    "Dec 2025"
  ],
  "kpi_cards": [
    {
      "label": "Total Revenue (YTD)",
      "value": 1313521.67,
      "format": "currency",
      "delta_label": "Dec 2025 vs Nov 2025",
      "delta_pct": 13.6
    },
    {
      "label": "Total Expenses (YTD)",
      "value": 1089872.37,
      "format": "currency",
      "delta_label": "Dec 2025 vs Nov 2025",
      "delta_pct": 12.6
    },
    {
      "label": "Net Profit (YTD)",
      "value": 223649.3,
      "format": "currency",
      "delta_label": "Dec 2025 vs Nov 2025",
      "delta_pct": 18.3
    },
    {
      "label": "Net Margin (latest month)",
      "value": 19.0,
      "format": "percent",
      "delta_label": "vs Nov 2025",
      "delta_pct": 0.8
    }
  ],
  "trend": {
    "labels": [
      "Jan 2025",
      "Feb 2025",
      "Mar 2025",
      "Apr 2025",
      "May 2025",
      "Jun 2025",
      "Jul 2025",
      "Aug 2025",
      "Sep 2025",
      "Oct 2025",
      "Nov 2025",
      "Dec 2025"
    ],
    "revenue": [
      92760.6,
      88814.29,
      92097.3,
      93647.8,
      87209.27,
      102454.16,
      108312.35,
      113549.51,
      97680.66,
      122967.35,
      147000.93,
      167027.45
    ],
    "expense": [
      81849.29,
      75393.37,
      75628.11,
      78390.93,
      67567.92,
      86005.61,
      96241.4,
      91790.98,
      85316.14,
      96194.23,
      120182.02,
      135312.37
    ],
    "profit": [
      10911.31,
      13420.92,
      16469.19,
      15256.87,
      19641.35,
      16448.55,
      12070.95,
      21758.53,
      12364.52,
      26773.12,
      26818.91,
      31715.08
    ]
  },
  "revenue_breakdown": {
    "labels": [
      "Jan 2025",
      "Feb 2025",
      "Mar 2025",
      "Apr 2025",
      "May 2025",
      "Jun 2025",
      "Jul 2025",
      "Aug 2025",
      "Sep 2025",
      "Oct 2025",
      "Nov 2025",
      "Dec 2025"
    ],
    "series": [
      {
        "name": "Apparel",
        "data": [
          12632.88,
          13706.85,
          13848.9,
          15510.37,
          16212.68,
          15778.49,
          15152.53,
          16797.32,
          16473.1,
          18429.84,
          24712.1,
          23720.38
        ]
      },
      {
        "name": "Beauty",
        "data": [
          5789.08,
          4077.89,
          5586.44,
          6575.81,
          5681.0,
          6686.34,
          7837.1,
          7983.03,
          7335.88,
          8639.44,
          9905.57,
          10987.08
        ]
      },
      {
        "name": "Electronics",
        "data": [
          46272.4,
          46177.02,
          45064.46,
          41645.06,
          40383.86,
          47539.21,
          54849.52,
          49524.6,
          45908.55,
          60603.94,
          64994.62,
          75129.03
        ]
      },
      {
        "name": "Home & Garden",
        "data": [
          13062.08,
          12720.13,
          15613.79,
          14172.2,
          10575.4,
          15634.59,
          13998.3,
          19606.13,
          13411.03,
          17831.13,
          25986.29,
          27565.47
        ]
      },
      {
        "name": "Sports & Outdoors",
        "data": [
          15004.16,
          12132.4,
          11983.71,
          15744.36,
          14356.33,
          16815.53,
          16474.9,
          19638.43,
          14552.1,
          17463.0,
          21402.35,
          29625.49
        ]
      }
    ]
  },
  "expense_breakdown": {
    "month": "Dec 2025",
    "labels": [
      "COGS",
      "Payroll & Ops",
      "Marketing & Ads",
      "Shipping & Fulfillment",
      "Returns & Refunds",
      "Platform & Tech",
      "Payment Processing"
    ],
    "values": [
      66143.93,
      20447.11,
      18674.05,
      12250.18,
      7361.6,
      5435.76,
      4999.74
    ]
  },
  "variance_by_month": [
    {
      "month": "Jan 2025",
      "revenue_actual": 92760.6,
      "revenue_budget": 85995.69,
      "revenue_variance_pct": 7.9,
      "expense_actual": 81849.29,
      "expense_budget": 84390.21,
      "expense_variance_pct": -3.0
    },
    {
      "month": "Feb 2025",
      "revenue_actual": 88814.29,
      "revenue_budget": 95589.22,
      "revenue_variance_pct": -7.1,
      "expense_actual": 75393.37,
      "expense_budget": 67234.05,
      "expense_variance_pct": 12.1
    },
    {
      "month": "Mar 2025",
      "revenue_actual": 92097.3,
      "revenue_budget": 94646.52,
      "revenue_variance_pct": -2.7,
      "expense_actual": 75628.11,
      "expense_budget": 76287.12,
      "expense_variance_pct": -0.9
    },
    {
      "month": "Apr 2025",
      "revenue_actual": 93647.8,
      "revenue_budget": 93619.32,
      "revenue_variance_pct": 0.0,
      "expense_actual": 78390.93,
      "expense_budget": 77005.7,
      "expense_variance_pct": 1.8
    },
    {
      "month": "May 2025",
      "revenue_actual": 87209.27,
      "revenue_budget": 86308.87,
      "revenue_variance_pct": 1.0,
      "expense_actual": 67567.92,
      "expense_budget": 67928.81,
      "expense_variance_pct": -0.5
    },
    {
      "month": "Jun 2025",
      "revenue_actual": 102454.16,
      "revenue_budget": 107548.72,
      "revenue_variance_pct": -4.7,
      "expense_actual": 86005.61,
      "expense_budget": 84507.39,
      "expense_variance_pct": 1.8
    },
    {
      "month": "Jul 2025",
      "revenue_actual": 108312.35,
      "revenue_budget": 104763.63,
      "revenue_variance_pct": 3.4,
      "expense_actual": 96241.4,
      "expense_budget": 90315.1,
      "expense_variance_pct": 6.6
    },
    {
      "month": "Aug 2025",
      "revenue_actual": 113549.51,
      "revenue_budget": 109347.28,
      "revenue_variance_pct": 3.8,
      "expense_actual": 91790.98,
      "expense_budget": 90284.92,
      "expense_variance_pct": 1.7
    },
    {
      "month": "Sep 2025",
      "revenue_actual": 97680.66,
      "revenue_budget": 93629.87,
      "revenue_variance_pct": 4.3,
      "expense_actual": 85316.14,
      "expense_budget": 89242.19,
      "expense_variance_pct": -4.4
    },
    {
      "month": "Oct 2025",
      "revenue_actual": 122967.35,
      "revenue_budget": 124019.05,
      "revenue_variance_pct": -0.8,
      "expense_actual": 96194.23,
      "expense_budget": 98085.28,
      "expense_variance_pct": -1.9
    },
    {
      "month": "Nov 2025",
      "revenue_actual": 147000.93,
      "revenue_budget": 162688.49,
      "revenue_variance_pct": -9.6,
      "expense_actual": 120182.02,
      "expense_budget": 118296.78,
      "expense_variance_pct": 1.6
    },
    {
      "month": "Dec 2025",
      "revenue_actual": 167027.45,
      "revenue_budget": 171098.79,
      "revenue_variance_pct": -2.4,
      "expense_actual": 135312.37,
      "expense_budget": 135583.45,
      "expense_variance_pct": -0.2
    }
  ],
  "latest_month_variance_detail": [
    {
      "type": "expense",
      "category": "Returns & Refunds",
      "amount_actual": 7361.6,
      "amount_budget": 6502.33,
      "variance": 859.2700000000004,
      "variance_pct": 13.2
    },
    {
      "type": "revenue",
      "category": "Apparel",
      "amount_actual": 23720.38,
      "amount_budget": 21915.68,
      "variance": 1804.7000000000007,
      "variance_pct": 8.2
    },
    {
      "type": "revenue",
      "category": "Sports & Outdoors",
      "amount_actual": 29625.49,
      "amount_budget": 32136.51,
      "variance": -2511.019999999997,
      "variance_pct": -7.8
    },
    {
      "type": "expense",
      "category": "Platform & Tech",
      "amount_actual": 5435.76,
      "amount_budget": 5079.85,
      "variance": 355.90999999999985,
      "variance_pct": 7.0
    },
    {
      "type": "expense",
      "category": "Marketing & Ads",
      "amount_actual": 18674.05,
      "amount_budget": 17708.41,
      "variance": 965.6399999999994,
      "variance_pct": 5.5
    },
    {
      "type": "expense",
      "category": "COGS",
      "amount_actual": 66143.93,
      "amount_budget": 69066.67,
      "variance": -2922.7400000000052,
      "variance_pct": -4.2
    },
    {
      "type": "revenue",
      "category": "Beauty",
      "amount_actual": 10987.08,
      "amount_budget": 11456.97,
      "variance": -469.8899999999994,
      "variance_pct": -4.1
    },
    {
      "type": "revenue",
      "category": "Electronics",
      "amount_actual": 75129.03,
      "amount_budget": 78259.9,
      "variance": -3130.8699999999953,
      "variance_pct": -4.0
    },
    {
      "type": "expense",
      "category": "Payment Processing",
      "amount_actual": 4999.74,
      "amount_budget": 4842.6,
      "variance": 157.13999999999942,
      "variance_pct": 3.2
    },
    {
      "type": "expense",
      "category": "Shipping & Fulfillment",
      "amount_actual": 12250.18,
      "amount_budget": 12093.49,
      "variance": 156.6900000000005,
      "variance_pct": 1.3
    },
    {
      "type": "revenue",
      "category": "Home & Garden",
      "amount_actual": 27565.47,
      "amount_budget": 27329.73,
      "variance": 235.7400000000016,
      "variance_pct": 0.9
    },
    {
      "type": "expense",
      "category": "Payroll & Ops",
      "amount_actual": 20447.11,
      "amount_budget": 20290.1,
      "variance": 157.01000000000204,
      "variance_pct": 0.8
    }
  ],
  "drilldown": {
    "Apparel": {
      "monthly_revenue": [
        12632.88,
        13706.85,
        13848.9,
        15510.37,
        16212.68,
        15778.49,
        15152.53,
        16797.32,
        16473.1,
        18429.84,
        24712.1,
        23720.38
      ],
      "monthly_orders": [
        142,
        147,
        149,
        160,
        160,
        159,
        161,
        167,
        180,
        185,
        269,
        258
      ],
      "sample_orders": [
        {
          "order_id": 104921,
          "date": "2025-09-22",
          "channel": "Website",
          "units": 3,
          "revenue": 289.92,
          "returned": false
        },
        {
          "order_id": 104057,
          "date": "2025-08-18",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 286.23,
          "returned": false
        },
        {
          "order_id": 105482,
          "date": "2025-10-17",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 275.08,
          "returned": false
        },
        {
          "order_id": 103023,
          "date": "2025-06-27",
          "channel": "Website",
          "units": 3,
          "revenue": 268.95,
          "returned": false
        },
        {
          "order_id": 106800,
          "date": "2025-12-21",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 266.89,
          "returned": false
        },
        {
          "order_id": 104690,
          "date": "2025-09-16",
          "channel": "Website",
          "units": 3,
          "revenue": 263.8,
          "returned": false
        },
        {
          "order_id": 101181,
          "date": "2025-03-04",
          "channel": "Website",
          "units": 3,
          "revenue": 258.54,
          "returned": false
        },
        {
          "order_id": 103985,
          "date": "2025-08-12",
          "channel": "Website",
          "units": 3,
          "revenue": 253.98,
          "returned": false
        },
        {
          "order_id": 105501,
          "date": "2025-10-13",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 252.35,
          "returned": false
        },
        {
          "order_id": 102253,
          "date": "2025-05-04",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 250.0,
          "returned": false
        },
        {
          "order_id": 105451,
          "date": "2025-10-26",
          "channel": "Website",
          "units": 3,
          "revenue": 249.78,
          "returned": false
        },
        {
          "order_id": 103946,
          "date": "2025-08-05",
          "channel": "Website",
          "units": 3,
          "revenue": 247.79,
          "returned": false
        },
        {
          "order_id": 103981,
          "date": "2025-08-07",
          "channel": "Website",
          "units": 3,
          "revenue": 246.89,
          "returned": false
        },
        {
          "order_id": 103268,
          "date": "2025-06-25",
          "channel": "Website",
          "units": 3,
          "revenue": 245.85,
          "returned": true
        },
        {
          "order_id": 101234,
          "date": "2025-03-15",
          "channel": "Website",
          "units": 3,
          "revenue": 244.26,
          "returned": false
        },
        {
          "order_id": 105484,
          "date": "2025-10-21",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 240.52,
          "returned": true
        },
        {
          "order_id": 104469,
          "date": "2025-08-28",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 240.07,
          "returned": false
        },
        {
          "order_id": 102664,
          "date": "2025-05-20",
          "channel": "Website",
          "units": 3,
          "revenue": 240.02,
          "returned": false
        },
        {
          "order_id": 100514,
          "date": "2025-01-05",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 239.41,
          "returned": false
        },
        {
          "order_id": 103059,
          "date": "2025-06-30",
          "channel": "Website",
          "units": 3,
          "revenue": 237.36,
          "returned": false
        },
        {
          "order_id": 103416,
          "date": "2025-07-04",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 236.19,
          "returned": false
        },
        {
          "order_id": 105265,
          "date": "2025-10-26",
          "channel": "Website",
          "units": 3,
          "revenue": 236.05,
          "returned": false
        },
        {
          "order_id": 105756,
          "date": "2025-10-30",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 235.99,
          "returned": true
        },
        {
          "order_id": 106801,
          "date": "2025-12-12",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 235.65,
          "returned": false
        },
        {
          "order_id": 103650,
          "date": "2025-07-13",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 233.62,
          "returned": false
        }
      ]
    },
    "Beauty": {
      "monthly_revenue": [
        5789.08,
        4077.89,
        5586.44,
        6575.81,
        5681.0,
        6686.34,
        7837.1,
        7983.03,
        7335.88,
        8639.44,
        9905.57,
        10987.08
      ],
      "monthly_orders": [
        83,
        65,
        91,
        99,
        89,
        106,
        109,
        110,
        111,
        117,
        144,
        159
      ],
      "sample_orders": [
        {
          "order_id": 107761,
          "date": "2025-12-30",
          "channel": "Website",
          "units": 3,
          "revenue": 219.48,
          "returned": false
        },
        {
          "order_id": 105779,
          "date": "2025-10-06",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 203.46,
          "returned": false
        },
        {
          "order_id": 105741,
          "date": "2025-10-21",
          "channel": "Website",
          "units": 3,
          "revenue": 199.25,
          "returned": false
        },
        {
          "order_id": 105649,
          "date": "2025-10-17",
          "channel": "Website",
          "units": 3,
          "revenue": 197.32,
          "returned": false
        },
        {
          "order_id": 105116,
          "date": "2025-09-15",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 191.98,
          "returned": false
        },
        {
          "order_id": 102654,
          "date": "2025-05-29",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 187.53,
          "returned": false
        },
        {
          "order_id": 107545,
          "date": "2025-12-31",
          "channel": "Website",
          "units": 3,
          "revenue": 187.28,
          "returned": false
        },
        {
          "order_id": 100338,
          "date": "2025-01-15",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 187.21,
          "returned": false
        },
        {
          "order_id": 104141,
          "date": "2025-08-30",
          "channel": "Website",
          "units": 3,
          "revenue": 182.85,
          "returned": false
        },
        {
          "order_id": 101698,
          "date": "2025-04-30",
          "channel": "Website",
          "units": 3,
          "revenue": 181.89,
          "returned": false
        },
        {
          "order_id": 105378,
          "date": "2025-10-25",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 179.5,
          "returned": false
        },
        {
          "order_id": 103367,
          "date": "2025-07-17",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 179.46,
          "returned": false
        },
        {
          "order_id": 102267,
          "date": "2025-05-29",
          "channel": "Website",
          "units": 3,
          "revenue": 178.12,
          "returned": false
        },
        {
          "order_id": 102818,
          "date": "2025-06-24",
          "channel": "Website",
          "units": 3,
          "revenue": 177.34,
          "returned": false
        },
        {
          "order_id": 107287,
          "date": "2025-12-05",
          "channel": "Website",
          "units": 3,
          "revenue": 177.32,
          "returned": false
        },
        {
          "order_id": 104175,
          "date": "2025-08-19",
          "channel": "Website",
          "units": 3,
          "revenue": 176.49,
          "returned": false
        },
        {
          "order_id": 103959,
          "date": "2025-08-20",
          "channel": "Website",
          "units": 3,
          "revenue": 173.14,
          "returned": false
        },
        {
          "order_id": 104285,
          "date": "2025-08-16",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 171.08,
          "returned": false
        },
        {
          "order_id": 104271,
          "date": "2025-08-08",
          "channel": "Website",
          "units": 3,
          "revenue": 170.31,
          "returned": false
        },
        {
          "order_id": 102495,
          "date": "2025-05-13",
          "channel": "Website",
          "units": 3,
          "revenue": 169.39,
          "returned": false
        },
        {
          "order_id": 105789,
          "date": "2025-10-14",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 168.68,
          "returned": false
        },
        {
          "order_id": 106270,
          "date": "2025-11-19",
          "channel": "Website",
          "units": 3,
          "revenue": 168.33,
          "returned": false
        },
        {
          "order_id": 106013,
          "date": "2025-11-23",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 166.41,
          "returned": false
        },
        {
          "order_id": 106403,
          "date": "2025-11-07",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 164.8,
          "returned": false
        },
        {
          "order_id": 102798,
          "date": "2025-06-17",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 164.12,
          "returned": false
        }
      ]
    },
    "Electronics": {
      "monthly_revenue": [
        46272.4,
        46177.02,
        45064.46,
        41645.06,
        40383.86,
        47539.21,
        54849.52,
        49524.6,
        45908.55,
        60603.94,
        64994.62,
        75129.03
      ],
      "monthly_orders": [
        131,
        141,
        128,
        126,
        120,
        140,
        155,
        143,
        138,
        174,
        198,
        226
      ],
      "sample_orders": [
        {
          "order_id": 103375,
          "date": "2025-07-24",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 994.53,
          "returned": false
        },
        {
          "order_id": 102066,
          "date": "2025-04-13",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 948.6,
          "returned": false
        },
        {
          "order_id": 102209,
          "date": "2025-05-05",
          "channel": "Website",
          "units": 3,
          "revenue": 910.3,
          "returned": false
        },
        {
          "order_id": 105441,
          "date": "2025-10-18",
          "channel": "Website",
          "units": 3,
          "revenue": 908.21,
          "returned": false
        },
        {
          "order_id": 101886,
          "date": "2025-04-27",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 902.51,
          "returned": false
        },
        {
          "order_id": 100297,
          "date": "2025-01-24",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 893.4,
          "returned": false
        },
        {
          "order_id": 100289,
          "date": "2025-01-20",
          "channel": "Website",
          "units": 3,
          "revenue": 881.22,
          "returned": false
        },
        {
          "order_id": 106356,
          "date": "2025-11-13",
          "channel": "Website",
          "units": 3,
          "revenue": 868.92,
          "returned": false
        },
        {
          "order_id": 104818,
          "date": "2025-09-01",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 866.69,
          "returned": false
        },
        {
          "order_id": 105238,
          "date": "2025-10-29",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 864.31,
          "returned": false
        },
        {
          "order_id": 104602,
          "date": "2025-09-02",
          "channel": "Website",
          "units": 3,
          "revenue": 863.55,
          "returned": false
        },
        {
          "order_id": 102816,
          "date": "2025-06-30",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 854.71,
          "returned": false
        },
        {
          "order_id": 101382,
          "date": "2025-03-09",
          "channel": "Website",
          "units": 3,
          "revenue": 853.82,
          "returned": false
        },
        {
          "order_id": 100263,
          "date": "2025-01-18",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 842.11,
          "returned": false
        },
        {
          "order_id": 105765,
          "date": "2025-10-12",
          "channel": "Website",
          "units": 3,
          "revenue": 841.43,
          "returned": false
        },
        {
          "order_id": 104073,
          "date": "2025-08-17",
          "channel": "Website",
          "units": 3,
          "revenue": 839.38,
          "returned": false
        },
        {
          "order_id": 102175,
          "date": "2025-05-19",
          "channel": "Website",
          "units": 3,
          "revenue": 839.12,
          "returned": false
        },
        {
          "order_id": 102884,
          "date": "2025-06-16",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 834.21,
          "returned": false
        },
        {
          "order_id": 105653,
          "date": "2025-10-10",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 832.89,
          "returned": false
        },
        {
          "order_id": 107074,
          "date": "2025-12-08",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 831.38,
          "returned": false
        },
        {
          "order_id": 106728,
          "date": "2025-11-17",
          "channel": "Website",
          "units": 3,
          "revenue": 826.06,
          "returned": true
        },
        {
          "order_id": 102944,
          "date": "2025-06-02",
          "channel": "Website",
          "units": 3,
          "revenue": 823.47,
          "returned": false
        },
        {
          "order_id": 101158,
          "date": "2025-03-19",
          "channel": "Website",
          "units": 3,
          "revenue": 823.38,
          "returned": false
        },
        {
          "order_id": 102380,
          "date": "2025-05-30",
          "channel": "Website",
          "units": 3,
          "revenue": 820.68,
          "returned": false
        },
        {
          "order_id": 103745,
          "date": "2025-07-23",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 816.93,
          "returned": false
        }
      ]
    },
    "Home & Garden": {
      "monthly_revenue": [
        13062.08,
        12720.13,
        15613.79,
        14172.2,
        10575.4,
        15634.59,
        13998.3,
        19606.13,
        13411.03,
        17831.13,
        25986.29,
        27565.47
      ],
      "monthly_orders": [
        87,
        90,
        109,
        93,
        77,
        104,
        100,
        127,
        92,
        123,
        179,
        186
      ],
      "sample_orders": [
        {
          "order_id": 103544,
          "date": "2025-07-19",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 427.45,
          "returned": false
        },
        {
          "order_id": 103882,
          "date": "2025-07-04",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 419.33,
          "returned": false
        },
        {
          "order_id": 104798,
          "date": "2025-09-07",
          "channel": "Website",
          "units": 3,
          "revenue": 418.54,
          "returned": false
        },
        {
          "order_id": 101586,
          "date": "2025-03-05",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 408.9,
          "returned": true
        },
        {
          "order_id": 104111,
          "date": "2025-08-20",
          "channel": "Website",
          "units": 3,
          "revenue": 405.4,
          "returned": false
        },
        {
          "order_id": 100576,
          "date": "2025-02-25",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 404.54,
          "returned": false
        },
        {
          "order_id": 102050,
          "date": "2025-04-11",
          "channel": "Website",
          "units": 3,
          "revenue": 394.24,
          "returned": false
        },
        {
          "order_id": 103003,
          "date": "2025-06-29",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 381.73,
          "returned": false
        },
        {
          "order_id": 102542,
          "date": "2025-05-13",
          "channel": "Website",
          "units": 3,
          "revenue": 377.28,
          "returned": false
        },
        {
          "order_id": 107637,
          "date": "2025-12-30",
          "channel": "Website",
          "units": 3,
          "revenue": 377.22,
          "returned": false
        },
        {
          "order_id": 105041,
          "date": "2025-09-20",
          "channel": "Website",
          "units": 3,
          "revenue": 374.42,
          "returned": false
        },
        {
          "order_id": 101623,
          "date": "2025-04-16",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 371.13,
          "returned": false
        },
        {
          "order_id": 101066,
          "date": "2025-03-10",
          "channel": "Website",
          "units": 3,
          "revenue": 370.59,
          "returned": false
        },
        {
          "order_id": 106445,
          "date": "2025-11-01",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 367.59,
          "returned": false
        },
        {
          "order_id": 107606,
          "date": "2025-12-17",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 363.64,
          "returned": false
        },
        {
          "order_id": 105520,
          "date": "2025-10-06",
          "channel": "Website",
          "units": 3,
          "revenue": 359.27,
          "returned": false
        },
        {
          "order_id": 100938,
          "date": "2025-02-13",
          "channel": "Website",
          "units": 3,
          "revenue": 358.92,
          "returned": false
        },
        {
          "order_id": 102994,
          "date": "2025-06-07",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 358.29,
          "returned": false
        },
        {
          "order_id": 104347,
          "date": "2025-08-17",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 346.78,
          "returned": false
        },
        {
          "order_id": 102335,
          "date": "2025-05-07",
          "channel": "Website",
          "units": 3,
          "revenue": 343.98,
          "returned": false
        },
        {
          "order_id": 103150,
          "date": "2025-06-24",
          "channel": "Website",
          "units": 3,
          "revenue": 343.52,
          "returned": false
        },
        {
          "order_id": 105509,
          "date": "2025-10-24",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 341.73,
          "returned": false
        },
        {
          "order_id": 106726,
          "date": "2025-11-23",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 340.62,
          "returned": false
        },
        {
          "order_id": 105592,
          "date": "2025-10-18",
          "channel": "Website",
          "units": 3,
          "revenue": 339.49,
          "returned": false
        },
        {
          "order_id": 101368,
          "date": "2025-03-17",
          "channel": "Website",
          "units": 3,
          "revenue": 338.13,
          "returned": false
        }
      ]
    },
    "Sports & Outdoors": {
      "monthly_revenue": [
        15004.16,
        12132.4,
        11983.71,
        15744.36,
        14356.33,
        16815.53,
        16474.9,
        19638.43,
        14552.1,
        17463.0,
        21402.35,
        29625.49
      ],
      "monthly_orders": [
        84,
        71,
        68,
        87,
        78,
        92,
        89,
        111,
        83,
        96,
        127,
        174
      ],
      "sample_orders": [
        {
          "order_id": 102304,
          "date": "2025-05-30",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 488.95,
          "returned": false
        },
        {
          "order_id": 103992,
          "date": "2025-08-19",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 485.94,
          "returned": false
        },
        {
          "order_id": 102806,
          "date": "2025-06-05",
          "channel": "Website",
          "units": 3,
          "revenue": 484.8,
          "returned": false
        },
        {
          "order_id": 100078,
          "date": "2025-01-01",
          "channel": "Website",
          "units": 3,
          "revenue": 484.52,
          "returned": false
        },
        {
          "order_id": 102423,
          "date": "2025-05-04",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 484.38,
          "returned": false
        },
        {
          "order_id": 102663,
          "date": "2025-05-23",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 479.27,
          "returned": false
        },
        {
          "order_id": 104759,
          "date": "2025-09-18",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 473.81,
          "returned": false
        },
        {
          "order_id": 104242,
          "date": "2025-08-01",
          "channel": "Website",
          "units": 3,
          "revenue": 473.14,
          "returned": false
        },
        {
          "order_id": 107436,
          "date": "2025-12-02",
          "channel": "Website",
          "units": 3,
          "revenue": 472.82,
          "returned": false
        },
        {
          "order_id": 101754,
          "date": "2025-04-01",
          "channel": "Website",
          "units": 3,
          "revenue": 471.46,
          "returned": false
        },
        {
          "order_id": 107323,
          "date": "2025-12-18",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 465.18,
          "returned": false
        },
        {
          "order_id": 102709,
          "date": "2025-06-29",
          "channel": "Website",
          "units": 3,
          "revenue": 463.74,
          "returned": false
        },
        {
          "order_id": 100301,
          "date": "2025-01-04",
          "channel": "Website",
          "units": 3,
          "revenue": 462.87,
          "returned": false
        },
        {
          "order_id": 106476,
          "date": "2025-11-08",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 460.63,
          "returned": false
        },
        {
          "order_id": 106264,
          "date": "2025-11-16",
          "channel": "Marketplace",
          "units": 3,
          "revenue": 458.71,
          "returned": false
        },
        {
          "order_id": 106051,
          "date": "2025-11-07",
          "channel": "Website",
          "units": 3,
          "revenue": 456.41,
          "returned": false
        },
        {
          "order_id": 103377,
          "date": "2025-07-13",
          "channel": "Website",
          "units": 3,
          "revenue": 455.99,
          "returned": false
        },
        {
          "order_id": 101362,
          "date": "2025-03-23",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 453.22,
          "returned": false
        },
        {
          "order_id": 107266,
          "date": "2025-12-07",
          "channel": "Website",
          "units": 3,
          "revenue": 448.98,
          "returned": false
        },
        {
          "order_id": 101381,
          "date": "2025-03-02",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 441.96,
          "returned": false
        },
        {
          "order_id": 102655,
          "date": "2025-05-09",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 435.02,
          "returned": false
        },
        {
          "order_id": 105826,
          "date": "2025-10-02",
          "channel": "Website",
          "units": 3,
          "revenue": 433.62,
          "returned": false
        },
        {
          "order_id": 104360,
          "date": "2025-08-17",
          "channel": "Website",
          "units": 3,
          "revenue": 433.16,
          "returned": false
        },
        {
          "order_id": 103399,
          "date": "2025-07-20",
          "channel": "Website",
          "units": 3,
          "revenue": 432.21,
          "returned": false
        },
        {
          "order_id": 107053,
          "date": "2025-12-27",
          "channel": "Mobile App",
          "units": 3,
          "revenue": 430.37,
          "returned": false
        }
      ]
    }
  },
  "product_lines": [
    "Apparel",
    "Beauty",
    "Electronics",
    "Home & Garden",
    "Sports & Outdoors"
  ]
};
