# %% [markdown]
# # SafeX Predictive Lead Scoring Model
#
# **Goal:** Score marketing/sales leads (university contacts, prospective clients)
# by likelihood to convert, so Business Development can prioritize follow-up.
#
# **Data note:** SafeX does not yet have a labeled historical lead dataset, so this
# notebook uses a **simulated** dataset (`data/leads.csv`, generated by
# `data/generate_data.py`) built from realistic B2B sales-development assumptions
# (faster response time, higher engagement, warm sources, and confirmed budget/authority
# correlate with conversion). The entire pipeline below — cleaning, EDA, modeling,
# evaluation, and the scoring function — is designed to work unchanged once real
# historical lead data is available: just point `DATA_PATH` at the real export.
#
# **Contents**
# 1. Load & clean data
# 2. Exploratory data analysis (EDA)
# 3. Train/test split & preprocessing
# 4. Train two models: Logistic Regression and Decision Tree
# 5. Evaluate & compare
# 6. Feature importance
# 7. Lead-scoring function + demo on new leads

# %%
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix, classification_report
)

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

DATA_PATH = "../data/leads.csv"
RANDOM_SEED = 42

# %% [markdown]
# ## 1. Load & clean data

# %%
df = pd.read_csv(DATA_PATH)
print(df.shape)
df.head()

# %%
df.info()

# %%
# Missing values
df.isna().sum()

# %% [markdown]
# `engagement_score` has a small amount of missingness (~3%), simulating real-world
# tracking gaps (e.g. email tracking pixel blocked). We'll impute with the median
# inside the modeling pipeline (fit only on training data, to avoid leakage).

# %%
# Basic sanity checks / cleaning
df["lead_id"] = df["lead_id"].astype(int)
assert df["converted"].isin([0, 1]).all()
df["company_size"] = df["company_size"].astype("category")
df["source"] = df["source"].astype("category")
df["industry"] = df["industry"].astype("category")

df.describe(include="all").T

# %% [markdown]
# ## 2. Exploratory Data Analysis

# %%
conv_rate = df["converted"].mean()
print(f"Overall conversion rate: {conv_rate:.1%}")

fig, ax = plt.subplots(figsize=(4, 4))
df["converted"].value_counts().sort_index().plot(
    kind="bar", ax=ax, color=["#c0504d", "#4f81bd"]
)
ax.set_xticklabels(["Not Converted (0)", "Converted (1)"], rotation=0)
ax.set_title("Class balance")
plt.tight_layout()
plt.savefig("../notebook/figs_class_balance.png", dpi=120)
plt.show()

# %%
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, col in zip(axes, ["company_size", "source", "industry"]):
    rate = df.groupby(col)["converted"].mean().sort_values(ascending=False)
    rate.plot(kind="bar", ax=ax, color="#4f81bd")
    ax.set_title(f"Conversion rate by {col}")
    ax.set_ylabel("Conversion rate")
    ax.tick_params(axis="x", rotation=45)
plt.tight_layout()
plt.savefig("../notebook/figs_categorical_conversion.png", dpi=120)
plt.show()

# %% [markdown]
# **Observation:** Referrals and University Partnerships convert notably better than
# Cold Outreach — consistent with the "warm lead" assumption baked into the simulation,
# and a reasonable prior for SafeX's real pipeline too.

# %%
numeric_cols = ["engagement_score", "response_time_hours", "prior_interactions", "lead_age_months"]
fig, axes = plt.subplots(1, 4, figsize=(18, 4))
for ax, col in zip(axes, numeric_cols):
    sns.boxplot(data=df, x="converted", y=col, ax=ax)
    ax.set_title(col)
    ax.set_xticklabels(["No", "Yes"])
plt.tight_layout()
plt.savefig("../notebook/figs_numeric_boxplots.png", dpi=120)
plt.show()

# %%
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
for ax, col in zip(axes, ["budget_confirmed", "attended_demo"]):
    rate = df.groupby(col)["converted"].mean()
    rate.plot(kind="bar", ax=ax, color="#9bbb59")
    ax.set_title(f"Conversion rate by {col}")
    ax.set_xticklabels(["No", "Yes"], rotation=0)
plt.tight_layout()
plt.savefig("../notebook/figs_binary_conversion.png", dpi=120)
plt.show()

# %%
corr = df[numeric_cols + ["budget_confirmed", "attended_demo", "converted"]].corr()
fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0, ax=ax)
ax.set_title("Correlation matrix (numeric features)")
plt.tight_layout()
plt.savefig("../notebook/figs_correlation.png", dpi=120)
plt.show()

# %% [markdown]
# **EDA takeaways:**
# - Lead **source** and **industry** show clear conversion-rate spread — categorical
#   features carry real signal.
# - **budget_confirmed**, **attended_demo**, and **prior_interactions** are positively
#   associated with conversion.
# - **response_time_hours** is negatively associated with conversion (slower reply → lower
#   conversion), matching common sales-development wisdom ("speed to lead").
# - Missing `engagement_score` values will be median-imputed in the pipeline.

# %% [markdown]
# ## 3. Train/test split & preprocessing

# %%
feature_cols = [
    "company_size", "source", "industry", "engagement_score",
    "response_time_hours", "prior_interactions", "budget_confirmed",
    "attended_demo", "lead_age_months",
]
X = df[feature_cols]
y = df["converted"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=RANDOM_SEED, stratify=y
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")
print(f"Train conversion rate: {y_train.mean():.1%} | Test conversion rate: {y_test.mean():.1%}")

# %%
categorical_features = ["company_size", "source", "industry"]
numeric_features = [
    "engagement_score", "response_time_hours", "prior_interactions",
    "budget_confirmed", "attended_demo", "lead_age_months",
]

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer(transformers=[
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features),
])

# %% [markdown]
# ## 4. Train models
#
# We train and compare two models as suggested by the task brief:
# - **Logistic Regression** — interpretable, gives clean coefficients (directional feature effects), fast, good baseline for lead scoring.
# - **Decision Tree** — captures non-linear interactions, gives an intuitive feature-importance ranking, easy to explain to non-technical stakeholders.

# %%
log_reg_pipe = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000, random_state=RANDOM_SEED)),
])
log_reg_pipe.fit(X_train, y_train)

tree_pipe = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(max_depth=4, min_samples_leaf=20, random_state=RANDOM_SEED)),
])
tree_pipe.fit(X_train, y_train)

print("Both models trained.")

# %% [markdown]
# ## 5. Evaluation & model comparison

# %%
def evaluate(pipe, name):
    y_pred = pipe.predict(X_test)
    y_proba = pipe.predict_proba(X_test)[:, 1]
    metrics = {
        "model": name,
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_proba),
    }
    return metrics, y_pred, y_proba

lr_metrics, lr_pred, lr_proba = evaluate(log_reg_pipe, "Logistic Regression")
dt_metrics, dt_pred, dt_proba = evaluate(tree_pipe, "Decision Tree")

results_df = pd.DataFrame([lr_metrics, dt_metrics]).set_index("model").round(3)
results_df

# %%
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
for ax, (y_pred, name) in zip(axes, [(lr_pred, "Logistic Regression"), (dt_pred, "Decision Tree")]):
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax,
                xticklabels=["Pred 0", "Pred 1"], yticklabels=["True 0", "True 1"])
    ax.set_title(f"Confusion matrix: {name}")
plt.tight_layout()
plt.savefig("../notebook/figs_confusion_matrices.png", dpi=120)
plt.show()

# %%
fig, ax = plt.subplots(figsize=(6, 5))
for proba, name in [(lr_proba, "Logistic Regression"), (dt_proba, "Decision Tree")]:
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    ax.plot(fpr, tpr, label=f"{name} (AUC={auc:.2f})")
ax.plot([0, 1], [0, 1], "k--", alpha=0.4)
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curve")
ax.legend()
plt.tight_layout()
plt.savefig("../notebook/figs_roc_curve.png", dpi=120)
plt.show()

# %%
print("=== Logistic Regression ===")
print(classification_report(y_test, lr_pred, target_names=["Not Converted", "Converted"]))
print("=== Decision Tree ===")
print(classification_report(y_test, dt_pred, target_names=["Not Converted", "Converted"]))

# %% [markdown]
# ### Model choice
#
# Both models perform reasonably well. We select **Logistic Regression** as the
# primary scoring model for this pilot because:
# - It outputs a smooth, well-calibrated **probability** (0-100% conversion likelihood),
#   which is exactly what a "lead score" should be — a decision tree's leaf-based
#   probabilities are much coarser (only as many distinct scores as leaves).
# - Coefficients are directly interpretable ("+1 prior interaction → X% higher odds
#   of conversion"), which is easy to explain to the BD team and to update in the
#   future.
# - It is less prone to overfitting on a modest-sized dataset like this one.
#
# The Decision Tree is kept in the notebook as a comparison model and because its
# rules (e.g. "if response_time_hours < 12 and budget_confirmed == 1 → high
# likelihood") are a useful, plain-English sanity check on the Logistic Regression's
# behavior.

# %%
fig, ax = plt.subplots(figsize=(20, 8))
plot_tree(
    tree_pipe.named_steps["classifier"],
    feature_names=tree_pipe.named_steps["preprocessor"].get_feature_names_out(),
    class_names=["Not Converted", "Converted"],
    filled=True, rounded=True, fontsize=8, ax=ax, max_depth=3,
)
ax.set_title("Decision Tree (top levels) — plain-English sanity check")
plt.tight_layout()
plt.savefig("../notebook/figs_decision_tree.png", dpi=120)
plt.show()

# %% [markdown]
# ## 6. Feature importance (top drivers of conversion)

# %%
feature_names = log_reg_pipe.named_steps["preprocessor"].get_feature_names_out()
coefs = log_reg_pipe.named_steps["classifier"].coef_[0]

coef_df = pd.DataFrame({"feature": feature_names, "coefficient": coefs})
coef_df["abs_coefficient"] = coef_df["coefficient"].abs()
coef_df = coef_df.sort_values("abs_coefficient", ascending=False)

top_n = 10
fig, ax = plt.subplots(figsize=(8, 6))
plot_df = coef_df.head(top_n).sort_values("coefficient")
colors = ["#c0504d" if c < 0 else "#4f81bd" for c in plot_df["coefficient"]]
ax.barh(plot_df["feature"], plot_df["coefficient"], color=colors)
ax.set_title(f"Top {top_n} features driving conversion (Logistic Regression coefficients)")
ax.set_xlabel("Coefficient (log-odds impact, standardized features)")
plt.tight_layout()
plt.savefig("../notebook/figs_feature_importance.png", dpi=120)
plt.show()

coef_df.head(10)

# %%
print("Top 3 features driving conversion:")
for i, row in coef_df.head(3).iterrows():
    direction = "increases" if row["coefficient"] > 0 else "decreases"
    print(f"  - {row['feature']}: {direction} conversion likelihood (coef={row['coefficient']:.2f})")

# %% [markdown]
# **Interpretation:** Positive coefficients push the predicted conversion probability
# up; negative coefficients push it down. Because numeric features were standardized,
# coefficient magnitude is roughly comparable across numeric features — one-hot
# categorical coefficients represent the effect of that category vs. the reference
# category. In this simulation the clearest drivers are typically **budget
# confirmation**, **lead source** (warm vs. cold), and **response time** — matching
# common B2B sales-development findings and worth validating against SafeX's real
# outcomes once available.

# %% [markdown]
# ## 7. Lead-scoring function
#
# This is the function the BD team's tooling (e.g. a CRM automation or the companion
# Streamlit app) would call for each new/updated lead.

# %%
def score_lead(lead: dict, pipe=log_reg_pipe) -> dict:
    """
    Score a single lead and return its conversion probability + priority tier.

    Parameters
    ----------
    lead : dict
        Must contain the same keys as `feature_cols`:
        company_size, source, industry, engagement_score, response_time_hours,
        prior_interactions, budget_confirmed, attended_demo, lead_age_months
    pipe : sklearn Pipeline
        A fitted model pipeline (defaults to the chosen Logistic Regression model).

    Returns
    -------
    dict with keys: score (0-100), priority ("High"/"Medium"/"Low"), probability (0-1)
    """
    lead_df = pd.DataFrame([lead])[feature_cols]
    proba = pipe.predict_proba(lead_df)[0, 1]
    score = round(proba * 100, 1)

    if proba >= 0.65:
        priority = "High"
    elif proba >= 0.35:
        priority = "Medium"
    else:
        priority = "Low"

    return {"score": score, "priority": priority, "probability": round(float(proba), 3)}


def score_leads_batch(leads_df: pd.DataFrame, pipe=log_reg_pipe) -> pd.DataFrame:
    """Vectorized version: score a DataFrame of leads and return it with score columns appended."""
    proba = pipe.predict_proba(leads_df[feature_cols])[:, 1]
    out = leads_df.copy()
    out["score"] = (proba * 100).round(1)
    out["probability"] = proba.round(3)
    out["priority"] = pd.cut(
        proba, bins=[-0.01, 0.35, 0.65, 1.01], labels=["Low", "Medium", "High"]
    )
    return out.sort_values("score", ascending=False)

# %% [markdown]
# ### Demo: scoring new sample leads

# %%
new_leads = [
    {
        # Warm university lead, fast responder, engaged, budget confirmed
        "company_size": "201-1000",
        "source": "University Partnership",
        "industry": "Higher Education",
        "engagement_score": 78,
        "response_time_hours": 4,
        "prior_interactions": 5,
        "budget_confirmed": 1,
        "attended_demo": 1,
        "lead_age_months": 1.0,
    },
    {
        # Cold outreach, slow to respond, low engagement
        "company_size": "1-50",
        "source": "Cold Outreach",
        "industry": "Other",
        "engagement_score": 22,
        "response_time_hours": 96,
        "prior_interactions": 0,
        "budget_confirmed": 0,
        "attended_demo": 0,
        "lead_age_months": 5.0,
    },
    {
        # Mid-tier: inbound website lead, moderate engagement, no budget confirmed yet
        "company_size": "51-200",
        "source": "Inbound Website",
        "industry": "Corporate Security",
        "engagement_score": 55,
        "response_time_hours": 20,
        "prior_interactions": 2,
        "budget_confirmed": 0,
        "attended_demo": 1,
        "lead_age_months": 2.0,
    },
    {
        # Conference lead, large government prospect, budget confirmed, hasn't seen demo yet
        "company_size": "1000+",
        "source": "Conference",
        "industry": "Government",
        "engagement_score": 60,
        "response_time_hours": 30,
        "prior_interactions": 3,
        "budget_confirmed": 1,
        "attended_demo": 0,
        "lead_age_months": 0.5,
    },
]

for i, lead in enumerate(new_leads, 1):
    result = score_lead(lead)
    print(f"Lead {i} [{lead['source']} / {lead['industry']}] -> "
          f"Score: {result['score']}/100  |  Priority: {result['priority']}  "
          f"|  P(convert)={result['probability']}")

# %%
new_leads_df = pd.DataFrame(new_leads)
scored_df = score_leads_batch(new_leads_df)
scored_df[["source", "industry", "score", "priority", "probability"]]

# %% [markdown]
# **Reading the output:** each new lead gets a `score` (0-100, higher = more likely to
# convert), a `probability` (the model's raw estimated conversion likelihood), and a
# `priority` tier (High ≥ 65, Medium 35-64, Low < 35) that BD reps can use directly to
# decide who to call first. Thresholds are configurable in `score_lead()` and should be
# tuned once real conversion data / rep capacity constraints are known.

# %% [markdown]
# ## Summary
#
# - Trained and compared two classifiers; selected **Logistic Regression** for its
#   probability calibration and interpretability, kept **Decision Tree** as a
#   sanity-check / explainability aid.
# - Test-set performance: see the `results_df` table in Section 5.
# - Top conversion drivers identified in Section 6 (budget confirmation, lead source,
#   response speed, in this simulated data).
# - Delivered a reusable `score_lead()` / `score_leads_batch()` function that plugs
#   directly into a CRM export, a spreadsheet, or the companion Streamlit app
#   (`app/streamlit_app.py`) for a BD rep to score leads interactively.
# - **Next step for a real pilot:** replace `data/leads.csv` with an export of
#   SafeX's actual historical leads (with a true `converted` outcome column) and
#   re-run this notebook top to bottom — the pipeline requires no code changes.
